apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |-
    {{- .Values.ConfigMap.data.redisConf | nindent 4 }}