apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.Role.rules | nindent 2 }}