apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.Service.spec.type }}
  ports:
    {{- toYaml .Values.Service.spec.ports | nindent 4  }}
  clusterIP: {{ .Values.Service.spec.clusterIP }}
  selector:
    {{- toYaml .Values.Service.spec.selector | nindent 4 }}