apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "redis.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "redis.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "redis.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
