# ---------------------------------------------------------------------------------------------------------
# base configuration
nameOverride: "mediocre-app-keycloak"
fullnameOverride: "mediocre-app-keycloak"
namespace: platform
role: "database"

# ---------------------------------------------------------------------------------------------------------
# serviceaccount
serviceAccount:
  name: ""
  create: true
  automount: true

# ---------------------------------------------------------------------------------------------------------
# role
Role:
  rules:
    - apiGroups: [""]
      resources: ["configmaps","secrets"]
      verbs: ["list","get"]

# ---------------------------------------------------------------------------------------------------------
# statefulset
StatefulSet:
  spec:
    podManagementPolicy: "OrderedReady"
    template:
      spec:
        containers:
          main:
            name: keycloak
            image: quay.io/keycloak/keycloak:26.0.0
            args: ["start-dev"]
            resources:
              requests:
                memory: "500M"
                cpu: 0.5
              limits:
                memory: "2G"
                cpu: 1.8
            env:
              - name: KEYCLOAK_ADMIN
                value: "admin"
              - name: KEYCLOAK_ADMIN_PASSWORD
                value: "admin"
              - name: KC_PROXY
                value: "edge"
            ports:
              - name: http
                containerPort: 8080
            readinessProbe:
              httpGet:
                path: /realms/master
                port: 8080
        tolerations:
          - key: "platform/role"
            operator: "Equal"
            value: "database"
            effect: "NoExecute"        
    selector:
      matchLabels:
        platform/role: database

# ---------------------------------------------------------------------------------------------------------
# service
Service:
  spec:
    type: NodePort
    ports:
      - targetPort: 8080
        port: 8080
        nodePort: 30180
    selector:
      app.kubernetes.io/name: mediocre-app-keycloak