# base convetion configuration
nameOverride: "mediocre-db-mariadb"
fullnameOverride: "mediocre-db-mariadb"
role: "database"

# ---------------------------------------------------------------------------------------------------------
# serviceaccount
serviceAccount:
  create: true
  automount: true
  name: ""

# ---------------------------------------------------------------------------------------------------------
# configmaps
configMapData:
  MARIADB_ROOT_PASSWORD: "Hell0D4tabase!"