apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  strategy:
    {{- toYaml .Values.Deployment.spec.strategy | nindent 4 }}
  template:
    metadata:
      name: {{ include "wordpress.fullname" . }}
      labels:
        {{- include "wordpress.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      initContainers:
      containers:
        - name: {{ .Values.Deployment.spec.template.spec.containers.main.name }}
          image: {{ .Values.Deployment.spec.template.spec.containers.main.image }}
          resources:
            {{- toYaml .Values.Deployment.spec.template.spec.containers.main.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "wordpress.fullname" . }}
          volumeMounts:
            {{- toYaml .Values.Deployment.spec.template.spec.containers.main.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.Deployment.spec.template.spec.volumes | nindent 8  }}
      securityContext:
        {{- toYaml .Values.Deployment.spec.template.spec.securityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.Deployment.spec.template.spec.imagePullSecrets | nindent 8  }}
      tolerations:
        {{- toYaml .Values.Deployment.spec.template.spec.tolerations | nindent 8 }}
  {{- if not .Values.HorizontalPodAutoscaler.enabled  }}
  replicas: {{ .Values.Deployment.spec.replicas }}
  {{- end }}
  selector:
    {{- toYaml .Values.Deployment.spec.selector | nindent 4 }}