apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wordpress.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "wordpress.fullname" . }}
  apiGroup: rbac.authorization.k8s.io