apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  podManagementPolicy: {{ .Values.StatefulSet.spec.podManagementPolicy }}
  template:
    metadata:
      name: {{ include "postgresql.fullname" . }}
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
    spec:
      ServiceAccountName: {{ include "postgresql.serviceAccountName" . }}
      containers:
        - name: {{ .Values.StatefulSet.spec.template.spec.containers.main.name }}
          image: {{ .Values.StatefulSet.spec.template.spec.containers.main.image }}
          args: {{ .Values.StatefulSet.spec.template.spec.containers.main.args }}
          resources:
            {{- toYaml .Values.StatefulSet.spec.template.spec.containers.main.resources | nindent 12 }}
          env:
            {{- toYaml .Values.StatefulSet.spec.template.spec.containers.main.env | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.StatefulSet.spec.template.spec.imagePullSecrets | nindent 8 }}
      tolerations:
        {{- toYaml .Values.StatefulSet.spec.template.spec.tolerations | nindent 8 }}
  replicas: {{ .Values.StatefulSet.spec.replicas }}
  selector:
    {{- toYaml .Values.StatefulSet.spec.selector | nindent 4  }}