apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  podManagementPolicy: {{ .Values.StatefulSet.podManagementPolicy }}
  template:
    metadata:
      name: {{ include "postgresql.fullname" . }}
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
    spec:
      ServiceAccountName: {{ include "postgresql.serviceAccountName" . }}
      containers:
        - name: {{ .Values.StatefulSet.containerMain.name }}
          image: {{ .Values.StatefulSet.containerMain.image }}
          resources:
            {{- toYaml .Values.StatefulSet.containerMain.resources | nindent 12 }}
          env:
            {{- toYaml .Values.StatefulSet.containerMain.env | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.StatefulSet.containerMain.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.StatefulSet.containerMain.volumes | nindent 8  }}
      securityContext:
        {{- toYaml .Values.StatefulSet.securityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.StatefulSet.imagePullSecrets | nindent 8 }}
      tolerations:
        {{- toYaml .Values.StatefulSet.tolerations | nindent 8 }}
  replicas: {{ .Values.StatefulSet.replicas }}
  selector:
    {{- toYaml .Values.StatefulSet.selector | nindent 4  }}