apiVersion: v1
kind: Service
metadata:
  name:  {{ include "mariadb.fullname" . }}-node
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ServiceNode.spec.type }}
  ports:
    {{- toYaml .Values.ServiceNode.spec.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.ServiceNode.spec.selector | nindent 4 }}