apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "keycloak.fullname" . }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "keycloak.fullname" . }}
      containers:
        - name: {{ .Values.Deployment.spec.template.spec.containers.main.name }}
          image: {{ .Values.Deployment.spec.template.spec.containers.main.image }}
          args: {{ .Values.Deployment.spec.template.spec.containers.main.args }}
          env:
            {{- toYaml .Values.Deployment.spec.template.spec.containers.main.env | nindent 12 }}
          ports:
            {{- toYaml .Values.Deployment.spec.template.spec.containers.main.ports | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.Deployment.spec.template.spec.containers.main.readinessProbe | nindent 12 }}
      tolerations:
        {{- toYaml .Values.Deployment.spec.template.spec.tolerations | nindent 8 }}
  replicas: {{ .Values.Deployment.spec.replicas }}
  selector:
    {{- toYaml .Values.Deployment.spec.selector | nindent 4  }}