apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
spec:
  ports:
    {{- toYaml .Values.Service.spec.ports | nindent 4 }}
  selector:
    {{- toYaml .Values.Service.spec.selector| nindent 4 }}