apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metrics.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metrics.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io