apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
spec:
  service:
    name: {{ include "metrics.fullname" . }}
    namespace: {{ .Values.namespace }}
  {{- toYaml .Values.APIService.spec | nindent 2 }}